/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const TinyLoading: typeof import('@opentiny/vue-loading')['default']
  const TinyModal: typeof import('@opentiny/vue-modal')['default']
  const TinyNotify: typeof import('@opentiny/vue-notify')['default']
}
